POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Te",
  "number": "TEST-NUMBER-00"
}

# {
#   "name": "Frank Grimes",
#   "number": "903823098109358"
# }

### ERRORS

## EMPTY
# {}


